# Generated by Django 6.0.2 on 2026-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='added_sugars',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='calcium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_fiber',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='iron',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='monounsaturated_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='polyunsaturated_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='potassium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='serving_size',
            field=models.CharField(default='1 serving', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='servings_per_container',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='total_sugars',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='trans_fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_d',
            field=models.FloatField(default=0.0),
        ),
    ]
