# Generated by Django 6.0.2 on 2026-03-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
