# Generated by Django 6.0.2 on 2026-03-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
