# Generated by Django 6.0.2 on 2026-03-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailotp_is_used_phoneotp_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='workouts_completed',
            field=models.IntegerField(default=0),
        ),
    ]
