# Generated by Django 6.0.2 on 2026-03-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dailystats_workouts_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='unread_count',
            field=models.IntegerField(default=0),
        ),
    ]
