# Generated by Django 6.0.2 on 2026-03-07 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_groupmember_unread_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_account', models.BooleanField(default=False)),
                ('show_profile_in_search', models.BooleanField(default=True)),
                ('show_activity_status', models.BooleanField(default=True)),
                ('share_workout_data', models.BooleanField(default=True)),
                ('share_diet_data', models.BooleanField(default=True)),
                ('share_progress_photos', models.BooleanField(default=False)),
                ('appear_on_leaderboards', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
