# Generated by Django 6.0.2 on 2026-03-07 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_privacysettings_two_factor_enabled_usersession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_goal', models.CharField(default='BuildMuscle', max_length=50)),
                ('current_weight', models.FloatField(default=72.0)),
                ('target_weight', models.FloatField(default=75.0)),
                ('weekly_goal_weight', models.FloatField(default=0.5)),
                ('current_body_fat', models.FloatField(default=18.0)),
                ('target_body_fat', models.FloatField(default=15.0)),
                ('muscle_mass_goal', models.FloatField(default=35.0)),
                ('workouts_per_week', models.IntegerField(default=4)),
                ('daily_step_goal', models.IntegerField(default=10000)),
                ('weekly_calorie_burn_goal', models.IntegerField(default=2000)),
                ('daily_calorie_target', models.IntegerField(default=2500)),
                ('protein_g', models.IntegerField(default=160)),
                ('carbs_g', models.IntegerField(default=250)),
                ('fats_g', models.IntegerField(default=70)),
                ('is_adaptive_mode_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
