# Generated by Django 6.0.2 on 2026-03-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usergoalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacysettings',
            name='two_factor_enabled',
        ),
    ]
