# Generated by Django 6.0.2 on 2026-03-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_privacysettings_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
