# Generated by Django 6.0.2 on 2026-03-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_achievement_rename_created_at_groupmember_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoalsettings',
            name='quiet_hours_from',
            field=models.CharField(default='22:00', max_length=5),
        ),
        migrations.AddField(
            model_name='usergoalsettings',
            name='quiet_hours_to',
            field=models.CharField(default='07:00', max_length=5),
        ),
    ]
