# Generated by Django 6.0.2 on 2026-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usergoalsettings_quiet_hours_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='carbs_consumed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='fat_consumed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='protein_consumed',
            field=models.FloatField(default=0.0),
        ),
    ]
