# Generated by Django 6.0.2 on 2026-03-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_dailystats_carbs_consumed_dailystats_fat_consumed_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailystats',
            table='daily_steps',
        ),
    ]
