# Generated by Django 6.0.2 on 2026-03-26 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_dailystats_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystats',
            name='calories_burned',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='calories_consumed',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='carbs_consumed',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='fat_consumed',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='protein_consumed',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='water_ml',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='workouts_completed',
        ),
    ]
