# Generated by Django
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_dailystats_calories_burned_and_more'),
    ]

    operations = [
        # 1. Rename 'user' field to 'userid'
        migrations.RenameField(
            model_name='dailystats',
            old_name='user',
            new_name='userid',
        ),
        # 2. Update the db_column to 'userid' if it wasn't already
        migrations.AlterField(
            model_name='dailystats',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL),
        ),
        # 3. Update unique_together to use the new field name
        migrations.AlterUniqueTogether(
            name='dailystats',
            unique_together={('userid', 'date')},
        ),
    ]
