# Generated by Django 6.0.2 on 2026-03-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_weightgoal_weightlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightlog',
            unique_together=set(),
        ),
    ]
