# Generated by Django 6.0.2 on 2026-03-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_waterintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightgoal',
            name='weekly_goal_weight',
            field=models.FloatField(default=0.5),
        ),
    ]
